### ISSUE TITLE
Can't find sources for the modified skulpt

### ISSUE THREAD

**Issue by twitwi** [js-parsons/js-parsons#25]
I wanted to update skulpt to get updates, and I realized that the bundled version is patch (at least to include unittestparsons).
What would be the best way to rebuild the modified skulpt (and maybe add functionalities on the python side)?

**Comment by vkaravir** [comment]
The version of skulpt is built from [this branch](https://github.com/vkaravir/skulpt). It is really out-of-date from the main skulpt repo, so it might be tricky to update.

**Comment by twitwi** [comment]
Ok, thanks for the link!
